name: go

on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  build:
    name: Build Goignis Binary
    runs-on: ubuntu-latest

    steps:
      - name: Setup Go
        uses: actions/setup-go@v5
        with:
          go-version: '1.24.4'

      - name: Clone Goignis
        run: |
          git clone https://github.com/crystalforceix/goignis.git
          cd goignis
          go build
          ls -lh


